Workaround for crash in WebView API on internal android.webkit.WebView.onCheckIsTextEditor call
java.lang.RuntimeException: Probable deadlock detected due to WebView API being called on incorrect thread while the UI thread is blocked