fix: webview crash on "onCheckIsTextEditor" call (#70)
* Workaround for crash in WebView API on internal
android.webkit.WebView.onCheckIsTextEditor call

java.lang.RuntimeException: Probable deadlock detected due to WebView API being called on incorrect thread while the UI thread is blocked

* Add Android API 16 Emulator to UI test matrix

* UI tests for API 16: specify emulator arch explicitly

* revert: matrix ui tests

* chore: bump to 3.3.3

* revert: ci

Co-authored-by: Sergiu Danalachi <danalachi.sergiu@gmail.com>